{% set version = "0.99b6" %}
{% set name = "tachyon" %}
{% set sha256 = "fec170e1286f6097f893f19e51ec597631cfd26d1fcc9ae8680ad9595b4598e6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://jedi.ks.uiuc.edu/~johns/raytracer/files/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - toolchain3
    - libpng >=1.6.28,<1.7
  run:
    - libpng >=1.6.28,<1.7

test:
  commands:
    # successful command returns 255 and unsuccessful command returns 0
    - tachyon | exit 0

about:
  home: http://jedi.ks.uiuc.edu/~johns/raytracer/
  license: BSD 3-Clause
  license_file: Copyright
  license_family: BSD
  summary: Parallel/Multiprocessor Ray Tracing Software

extra:
  recipe-maintainers:
    - isuruf
