travis:
  secure:
    BINSTAR_TOKEN: NCa7RJXJfshzwsjQkh3dF/nWNK+bxTEmI22kYyOSlJtw4QTgTZG0CHlzL5VmaszB0Z0Y3gYhdUrRB2ShAUB3/8BRnhref/M3pD3TsCLi0esF7aVO2jAmR2CVHjp4827FCwFzRkajDsELzdsFObv9vJrhku8WyMSPo3TyuUBNvxjEgdQHnndDQ81WWgCUzEnmQTBe8Dq8EA2OjOmnJORzueQkCgmwTRjBssF+ai69XM3YJTxixrVK1szfMHi0nTekE4CzgHRCGwrAEb/dyMpRts3L1Zj07jlkud6Kydd9RgVDyxsc4sSAhj4DX+zPDKGRaZBTw3qrxLP6+yLK5W+h/Vyb14jGrILMuTLfaDKc03DaiCOB3dU6wuacBKgWykkI00tUkW8yA5+SL6fgtB7ZEo1xQwlVXxl9Mg/tY7jWvIl6VNhCPZuqLTFozdxD2VnHFDc64o5LTTfmI59iijt/NiJr02VcYGGIHAI5GTRUl6I7f/Eyz5yWRHbupvxfsZLGbthUJpTtLQNlpBv5oVTUYHRUPqS+SDvubm6+gML4ouc6UwL2HMdQC1Q3G/cDyjmMtTr51y3kGO2IBzF+GJQ6pchd3umCddNP3CkEvBC/sEjVYJuxKl2O8qyjUjx3KH8CwzcBD2PAQqhNGbmwXa56aqzK+DCNqTzLYPsXKcynD2A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
