appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: Xr+yC+tisQq8Iy/DSX1Nliiruy+cAGvV7CVN6OjtLWPqiFA9kRZCPg4lkarCIbJn/yn+fXhiJSy61caXgLoTt77IhbCV7bV/SOTkdISRy9T40ztkp+bxsMGhysRPrlyHc7Mhjq2RB3kL+Crl0DuuL83HlIeBhJyYlCHqux5Vkrl3vChMcyrQrJ5gc0SKA3bPM8zkAnUBk4wgO666kIBX4e61dKeGTJ2efqy/9pbKn8rPEsvBeNHYQA13OdxMkO0aBWXvan/rbOlcuHM/afXyPyz0wUR5Is1Ii7eEywx9X7feRdA54D1mJ0tnQvn133ENdGBi9V0TpHDxEJedrMnxc7qdh+Ng1eMDMZsdbICz3phMpY8MtZYa7cYySXuVzs4MFyHK18uSNxQCQ8zvfZE+8hs0kgABOkhq6a8fR1iDOyGmPPnzuwHyEJ+LpZc1rfn+oQJnDV2cyD5jORPe0mEeFuPP8x54hKHrL7YNvnZLHnvcMWLonQUP6IKF9b12oO6jHwYb5krupDR/4qHJEb3rgXO49SQ6GLucEOXIJ6evD6ZYw7QljJo5EciTwvKNYoysuPDDYov7iR0iw45QYeCwCoIM51SHJrtXcR6g1n0nB2AZoVXPRoXif2tytbaZlWwooac1qehDiXRloaFavGgVgb9/siL4+S1WzL1bppZ/xDs=}
conda_forge_output_validation: true
